version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProjectTest3Project
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/ExternalTest1Project
  gitUsername: y509522
  gitBranch: main
